language: php

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION=3.0.* #php >=5.5.9

before_install:
  - export SYMFONY_DEPRECATIONS_HELPER=weak #set this to "strict" to make build fail on deprecation messages
  - composer self-update
  - mv composer.json composer.json.bck
  - sed 's/${env:SYMFONY_VERSION}/'$SYMFONY_VERSION'/g' composer-template.json > composer.json #replace composer dependencies with actual symfony version

install:
  - composer update --prefer-dist --no-interaction

after_install:
  - mv composer.json.bck composer.json

script: vendor/bin/phpunit --coverage-text

notifications:
  email:
    - travis-ci@kitpages.fr
